
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import { Poppins, Roboto_Mono } from 'next/font/google';

export const roboto = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400',  '700'],
  style: ['normal', 'italic'],
  preload: true,
  variable: '--font-roboto-mono',
});

export const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  preload: true,
  variable: '--font-poppins',
});

export const metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="night">
      <body
        className={`${poppins.variable}  antialiased bg-base-300`}
      >
        <Navbar />
        <main className=" bg-base-300 font-poppins">{children}</main>
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
